### ISSUE TITLE
Able to determine chunk progress (last bucket of stream) ?

### ISSUE THREAD

**Issue by locksem** [clue/stream-filter#41]
Is there any way to determine whether the current chunk is the last in the stream? 

In my case, I need to perform some transformation to only the very last chunk of data. In my current own-rolled filter, I'd be able to keep track of the current consumed amount to determine whether the current bucket were the last in the stream and treat it accordingly. It would be fantastic to be able to use this library, as it solves some other issues with my current filters.

Many thanks

**Comment by clue** [comment]
@locksem Thanks for bringing this up, good question!

Here's the relevant section from the readme:

> If the $callback accepts invocation without parameters, then this signature will be invoked once ending (flushing) the filter:
> 
> ```php
> Filter\append($stream, function ($chunk = null) {
>     if ($chunk === null) {
>         // will be called once ending the filter
>         return 'end';
>     }
>     // will be called each time you read or write a $chunk to/from the stream
>     return $chunk;
> });
> 
> fclose($stream);
> ```

I hope this helps :+1:
