### ISSUE TITLE
PHP 8.1 Deprecation: Clue\StreamFilter\CallbackFilter::onClose() should either be compatible with php_user_filter::onClose()

### ISSUE THREAD

**Issue by rodrigoaguilera** [clue/stream-filter#44]
When I run this library with php 8.1.0 I get

```
Return type of Clue\StreamFilter\CallbackFilter::onClose() should either be compatible with php_user_filter::onClose(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice 
in /vendor/clue/stream-filter/src/CallbackFilter.php:32
```

I think if compatibility with php 5 is still desirable the attribute annotation should be added.

**Comment by clue** [comment]
@rodrigoaguilera Thanks for reporting, I've just filed #45 to address this for the upcoming release :+1:

**Comment by clue** [comment]
@pataar I'm sure you're going to like v1.6.0 has just been released! :shipit:  I hope this helps! If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️
